[phases.setup]
# Remove apt packages to prevent GLIBC issues
aptPkgs = []

[variables]
NODE_VERSION = "23.3.0"
PNPM_VERSION = "9.14.4"

[phases.install]
cmds = [
    """
    # Download and install Node.js 23.3.0 binary
    cd /tmp && \
    curl -O https://nodejs.org/dist/v23.3.0/node-v23.3.0-linux-x64.tar.xz && \
    tar -xf node-v23.3.0-linux-x64.tar.xz && \
    cp -r node-v23.3.0-linux-x64/* /usr && \
    node --version && \
    # Install PNPM and dependencies
    npm install -g pnpm@9.14.4 && \
    pnpm --version && \
    cd /app && \
    pnpm install --frozen-lockfile
    """
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"