[phases.setup]
aptPkgs = [
    "python3",
    "python-is-python3"
]

[variables]
NODE_VERSION = "23.3.0"
PNPM_VERSION = "9.14.4"
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"

[phases.install]
cmds = [
    # Install Node.js
    "curl -fsSL https://nodejs.org/dist/v23.3.0/node-v23.3.0-linux-x64.tar.xz -o /tmp/node.tar.xz",
    "tar -xf /tmp/node.tar.xz -C /tmp",
    "cp -r /tmp/node-v23.3.0-linux-x64/* /usr/local",
    "node --version",
    # Install PNPM
    "npm install -g pnpm@9.14.4",
    "pnpm --version",
    # Verify Python installation
    "python --version",
    # Install dependencies
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"