[phases.setup]
aptPkgs = [
    "python3",
    "python-is-python3",
    # Playwright dependencies
    "libnss3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libgbm1",
    "libasound2",
    "libpangocairo-1.0-0",
    "libxss1",
    "libxshmfence1",
    "libglu1"
]

[variables]
NODE_VERSION = "23.3.0"
PNPM_VERSION = "9.14.4"
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PORT = "3001"

[phases.install]
cmds = [
    # Remove existing Node.js
    "rm -rf /usr/local/bin/node /usr/local/bin/npm",
    # Install Node.js 23
    "curl -fsSL https://nodejs.org/dist/v23.3.0/node-v23.3.0-linux-x64.tar.xz -o /tmp/node.tar.xz",
    "tar -xf /tmp/node.tar.xz -C /tmp",
    "cp -r /tmp/node-v23.3.0-linux-x64/* /usr/local",
    # Verify Node.js version
    "node --version",
    # Install PNPM
    "npm install -g pnpm@9.14.4",
    "pnpm --version",
    # Install dependencies
    "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm install --frozen-lockfile --ignore-scripts"
]

[phases.build]
cmds = [
    "node --version > .nodeversion",
    "pnpm run build"
]

[start]
cmd = """
node --version && \
export PATH=/usr/local/bin:$PATH && \
cd /app && \
pnpm start
"""